/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forme;

import domen.FakturaFizickoLice;
import domen.JedinicaMere;
import domen.StavkaFakture;
import domen.Usluga;
import java.util.List;
import javax.swing.JOptionPane;
import pl.kontroler.Kontroler;

public class FmIzmenaStavkeFak extends javax.swing.JFrame {

    /**
     * Creates new form FmUnosStavke
     */
     FmStavke stavka;
     public FmIzmenaStavkeFak(java.awt.Frame parent, boolean modal,  FmStavke stavka) {
        this.stavka=stavka;
         initComponents();
         jTxtBrRacuna.setEditable(false);
         jTxtRbrStavke.setEditable(false);
         srediFormu();
    }

    private FmIzmenaStavkeFak() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtRbrStavke = new javax.swing.JTextField();
        jTxtKolicina = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtJedMereID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtUsluga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTxtBrRacuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Broj racuna");

        jLabel2.setText("RbrStavke");

        jLabel3.setText("Kolicina");

        jLabel4.setText("Jedinica mere ID");

        jLabel5.setText("Usluga ID");

        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtRbrStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jTxtKolicina)
                            .addComponent(jTxtJedMereID)
                            .addComponent(jTxtUsluga)
                            .addComponent(jTxtBrRacuna)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtBrRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTxtRbrStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTxtJedMereID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FakturaFizickoLice r = new FakturaFizickoLice();
        
        int brr=Integer.parseInt(jTxtBrRacuna.getText().trim());

        r.setBrojRacuna(brr);
        
        
        int rbr = Integer.parseInt(jTxtRbrStavke.getText().trim());

        int kol = Integer.parseInt(jTxtKolicina.getText().trim());
        
        
        JedinicaMere jm=new JedinicaMere();
        int jmid=Integer.parseInt(jTxtJedMereID.getText().trim());
        jm.setJmId(jmid);
        
        Usluga us=new Usluga();
        
        int usid=Integer.parseInt(jTxtUsluga.getText().trim());
        
        us.setUslugaId(usid);
        
        StavkaFakture k = new StavkaFakture(rbr,r,kol,jm,us);

        try {
            Kontroler.vratiInstancuKontrolera().izmeniStavkuFakture(k);
            JOptionPane.showMessageDialog(this, "Stavka je uspesno izmenjena");
            //   osvezi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaStavkeFak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaStavkeFak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaStavkeFak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaStavkeFak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmIzmenaStavkeFak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtBrRacuna;
    private javax.swing.JTextField jTxtJedMereID;
    private javax.swing.JTextField jTxtKolicina;
    private javax.swing.JTextField jTxtRbrStavke;
    private javax.swing.JTextField jTxtUsluga;
    // End of variables declaration//GEN-END:variables
 
     private void srediFormu() {
         centrirajFormu();
        StavkaFakture k = (StavkaFakture) Kontroler.vratiInstancuKontrolera().getMapa().get("stavka_izabran");
        prikaziStavku(k);
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void prikaziStavku(StavkaFakture k) {
      jTxtBrRacuna.setText(k.getFaktura().getBrojRacuna()+"");
      jTxtRbrStavke.setText(k.getRbrStavke()+ "");
     jTxtKolicina.setText(k.getKolicina()+ "");
     jTxtUsluga.setText(k.getUsluga().getUslugaId()+ "");
    
     jTxtJedMereID.setText(k.getJedinicaMere().getJmId()+"");
       
    }

    private void osvezi() {
         if (stavka != null) {
            stavka.osvezi();
        }
    }

}
