/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forme;

import domen.Rezervacija;
import domen.RezervisaneSobe;
import javax.swing.JOptionPane;
import pl.kontroler.Kontroler;


public class FmIzmenaRS extends javax.swing.JFrame {

    /**
     * Creates new form FmIzmenaRS
     */
    FmRezSobe rezSobe;
     public FmIzmenaRS(java.awt.Frame parent, boolean modal,  FmRezSobe rezSobe) {
        this.rezSobe=rezSobe;
         initComponents();
         jTxtBrRez.setEditable(false);
         jTxtSobaID.setEditable(false);
        //jcmbBrojRezervacije.setEditable(false);
         srediFormu();
    }
    
    public FmIzmenaRS() {
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtBrSobe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTxtSobaID = new javax.swing.JTextField();
        jTxtBrOdraslih = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtBrDece = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtIznos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNapomena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtBrRez = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Iznos");

        jLabel6.setText("Napomena");

        jLabel7.setText("BrojSobe");

        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Broj rezervacije");

        jLabel2.setText("SobaID");

        jLabel3.setText("Broj odraslih");

        jTxtNapomena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxtNapomenaMousePressed(evt);
            }
        });
        jTxtNapomena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNapomenaKeyPressed(evt);
            }
        });

        jLabel4.setText("Broj dece");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtSobaID)
                            .addComponent(jTxtBrOdraslih)
                            .addComponent(jTxtBrDece)
                            .addComponent(jTxtIznos)
                            .addComponent(jTxtNapomena)
                            .addComponent(jTxtBrSobe, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jTxtBrRez)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtBrRez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTxtSobaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTxtBrOdraslih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTxtBrDece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtBrSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Rezervacija r = (Rezervacija) jcmbBrojRezervacije.getSelectedItem();

        int sobID = Integer.parseInt(jTxtSobaID.getText().trim());

         int brRez = Integer.parseInt(jTxtBrRez.getText().trim());
       
      
        
        int brOd = Integer.parseInt(jTxtBrOdraslih.getText().trim());
        int brDec = Integer.parseInt(jTxtBrDece.getText().trim());
        int iznos= Integer.parseInt(jTxtIznos.getText().trim());

        String naziv = jTxtNapomena.getText();
        int brSo= Integer.parseInt(jTxtBrSobe.getText().trim());

      //  RezervisaneSobe k = new RezervisaneSobe(r,sobID,brOd,brDec,iznos,naziv,brSo);

        Rezervacija r=new Rezervacija();
        r.setBrojRezervacije(brRez);
        RezervisaneSobe re=new RezervisaneSobe();
                re.setRezervacija(r);
        re.setSobaID(sobID);
        re.setBrojOdraslih(brOd);
        re.setBrojDece(brDec);
        re.setIznos(iznos);
       // re.setNapomena(naziv);
        re.setBrojSobe(brSo);
        try {
            Kontroler.vratiInstancuKontrolera().izmeniRezervisanuSobu(re);
            JOptionPane.showMessageDialog(this, "Rezervisana soba je uspesno izmenjena");
            
               osvezi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtNapomenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtNapomenaMousePressed
       
      //    jTxtNapomena.setEditable(false);

        int sobID = Integer.parseInt(jTxtSobaID.getText().trim());

         int brRez = Integer.parseInt(jTxtBrRez.getText().trim());
       
      
        
        int brOd = Integer.parseInt(jTxtBrOdraslih.getText().trim());
        int brDec = Integer.parseInt(jTxtBrDece.getText().trim());
        int iznos= Integer.parseInt(jTxtIznos.getText().trim());

        String naziv = jTxtNapomena.getText();
        int brSo= Integer.parseInt(jTxtBrSobe.getText().trim());

      //  RezervisaneSobe k = new RezervisaneSobe(r,sobID,brOd,brDec,iznos,naziv,brSo);

        Rezervacija r=new Rezervacija();
        r.setBrojRezervacije(brRez);
        RezervisaneSobe re=new RezervisaneSobe();
                re.setRezervacija(r);
        re.setSobaID(sobID);
        re.setBrojOdraslih(brOd);
        re.setBrojDece(brDec);
        re.setIznos(iznos);
        re.setNapomena(naziv);
        re.setBrojSobe(brSo);
        try {
            Kontroler.vratiInstancuKontrolera().izmeniRezervisanuSobu2(re);
                    //jTxtNapomena.setEditable(false);

           // jButton1.setVisible(false);
          //  JOptionPane.showMessageDialog(this, "Rezervisana soba je uspesno izmenjena");
            
               //osvezi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }     }//GEN-LAST:event_jTxtNapomenaMousePressed

    private void jTxtNapomenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNapomenaKeyPressed

        int sobID = Integer.parseInt(jTxtSobaID.getText().trim());

         int brRez = Integer.parseInt(jTxtBrRez.getText().trim());
       
      
        
        int brOd = Integer.parseInt(jTxtBrOdraslih.getText().trim());
        int brDec = Integer.parseInt(jTxtBrDece.getText().trim());
        int iznos= Integer.parseInt(jTxtIznos.getText().trim());

        String naziv = jTxtNapomena.getText();
        int brSo= Integer.parseInt(jTxtBrSobe.getText().trim());

      //  RezervisaneSobe k = new RezervisaneSobe(r,sobID,brOd,brDec,iznos,naziv,brSo);

        Rezervacija r=new Rezervacija();
        r.setBrojRezervacije(brRez);
        RezervisaneSobe re=new RezervisaneSobe();
                re.setRezervacija(r);
        re.setSobaID(sobID);
        re.setBrojOdraslih(brOd);
        re.setBrojDece(brDec);
        re.setIznos(iznos);
        re.setNapomena(naziv);
        re.setBrojSobe(brSo);
            //jTxtNapomena.setEditable(false);

        try {
            Kontroler.vratiInstancuKontrolera().izmeniRezervisanuSobu2(re);

           // jButton1.setVisible(false);
          //  JOptionPane.showMessageDialog(this, "Rezervisana soba je uspesno izmenjena");
            
               //osvezi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }     }//GEN-LAST:event_jTxtNapomenaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmIzmenaRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmIzmenaRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTxtBrDece;
    private javax.swing.JTextField jTxtBrOdraslih;
    private javax.swing.JTextField jTxtBrRez;
    private javax.swing.JTextField jTxtBrSobe;
    private javax.swing.JTextField jTxtIznos;
    private javax.swing.JTextField jTxtNapomena;
    private javax.swing.JTextField jTxtSobaID;
    // End of variables declaration//GEN-END:variables

 private void srediFormu() {
         centrirajFormu();
        RezervisaneSobe k = (RezervisaneSobe) Kontroler.vratiInstancuKontrolera().getMapa().get("rezsoba_izabran");
        prikaziRezSobu(k);
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void prikaziRezSobu(RezervisaneSobe k) {
       // jcmbBrojRezervacije.setSelectedItem(k.getRezervacija());
      jTxtBrRez.setText(k.getRezervacija().getBrojRezervacije()+"");
      jTxtSobaID.setText(k.getSobaID()+ "");
     jTxtBrOdraslih.setText(k.getBrojOdraslih()+ "");
     jTxtBrDece.setText(k.getBrojDece()+ "");
     jTxtIznos.setText(k.getIznos()+ "");
     jTxtNapomena.setText(k.getNapomena());
     jTxtBrSobe.setText(k.getBrojSobe()+"");
       
    }

    private void osvezi() {
         if (rezSobe != null) {
            rezSobe.osvezi();
        }
    }

}
