/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Gost;
import domen.Kupac;
import domen.Rezervacija;
import domen.Zaposleni;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Clock;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pl.kontroler.Kontroler;

public class FmRezervacijaIzmena extends javax.swing.JFrame {

    /**
     * Creates new form FmRezervacijaIzmena
     */
    FmRezervacija rezervacija;
    public FmRezervacijaIzmena(java.awt.Frame parent, boolean modal,  FmRezervacija rezervacija){
        this.rezervacija=rezervacija;
        initComponents();
        jtxtBrojRez.setEditable(false);
        jtxtDatOD.setEditable(false);
        jtxtDatDO.setEditable(false);
        srediFormu();
    }

    public FmRezervacijaIzmena() {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnIzmeniNar = new javax.swing.JButton();
        jtxtNacinRezervisanja = new javax.swing.JTextField();
        jtxtDatDO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtBrojRez = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtDatOD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtNapomena = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtTipPansiona = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtNazivGosta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtGostID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtImePrez = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtNazGosta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtKontakt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtnIzmeniNar.setText("Izmeni rezervaciju");
        jbtnIzmeniNar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniNarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nacin rezervisanja");

        jLabel1.setText("Broj rezervacije");

        jtxtBrojRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBrojRezActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum od:");

        jLabel3.setText("Datum do:");

        jLabel13.setText("Napomena");

        jTxtNapomena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNapomenaActionPerformed(evt);
            }
        });

        jLabel15.setText("Tip pansiona");

        jLabel16.setText("Naziv gosta");

        jTxtNazivGosta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtNazivGostaMouseClicked(evt);
            }
        });

        jLabel10.setText("PODACI O GOSTU");

        jLabel11.setText("Gost ID");

        jLabel14.setText("Ime i prezime");

        jLabel5.setText("Naziv gosta");

        jLabel6.setText("Kontakt");

        jTxtKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtKontaktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jtxtBrojRez, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(jtxtDatOD, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDatDO, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtGostID, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jtxtNacinRezervisanja))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtTipPansiona, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNazivGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtKontakt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jTxtImePrez)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(25, 25, 25)
                                        .addComponent(jTxtNazGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jbtnIzmeniNar)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtBrojRez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtDatOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtDatDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtNacinRezervisanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jTxtTipPansiona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtNazivGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGostID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jTxtImePrez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtNazGosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jbtnIzmeniNar)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBrojRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBrojRezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBrojRezActionPerformed

    private void jTxtNapomenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNapomenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNapomenaActionPerformed

    private void jTxtKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtKontaktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtKontaktActionPerformed

    private void jbtnIzmeniNarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniNarActionPerformed
 
            int brojRez = Integer.parseInt(jtxtBrojRez.getText().trim());
          //  SimpleDateFormat sdf = new SimpleDateFormat("dd-MM.yyyy.");
            // java.sql.Date datumOd = new java.util.Date(jtxtDatOD.getText());
            // java.util.Date datumDo = new java.util.Date(jtxtDatDO.getText());
            
 //  Date datumOd=null;
  // Date datumDo=null;
            
   //   try {
       //  datumOd=new SimpleDateFormat("dd-MM-yyyy").parse("10-12-2019");
         // datumDo = sdf.parse(jtxtDatOD.getText());
         
      //   datumDo=new SimpleDateFormat("dd-MM-yyyy").parse("12-12-2019");

  //     } catch (ParseException ex) {
       //    Logger.getLogger(FmRezervacijaIzmena.class.getName()).log(Level.SEVERE, null, ex);
     
    
  //     }
            String nacinRez=jtxtNacinRezervisanja.getText();
            String napom=jTxtNapomena.getText();
           
//            int kupacID = Integer.parseInt(jtxtKupacID.getText().trim());
            String tip=jTxtTipPansiona.getText();
            String nnaz=jTxtNazivGosta.getText();
        
        
            Gost g=new Gost();
            g.setGostID(Integer.parseInt(jTxtGostID.getText()));
                  
        
        Rezervacija n = new Rezervacija();
        n.setBrojRezervacije(brojRez);
    //    n.setDatumOd(datumOd);
      //  n.setDatumDo(datumDo);
        n.setNacinRezervisanja(nacinRez);
        n.setNapomena(napom);
        n.setTipPansiona(tip);
         n.setNazivGosta(nnaz);
        n.setGost(g);
        
        
          
       try {
            Kontroler.vratiInstancuKontrolera().izmeniRezervaciju(n);
            JOptionPane.showMessageDialog(this, "Rezervacija je uspesno izmenjena");
            osvezi();
      } catch (Exception ex) {
        //  JOptionPane.showMessageDialog(null, ex.getMessage());

          ex.getMessage();
       }
        
        
    
    }//GEN-LAST:event_jbtnIzmeniNarActionPerformed

    private void jTxtNazivGostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtNazivGostaMouseClicked
          int brojRez = Integer.parseInt(jtxtBrojRez.getText().trim());

            String nacinRez=jtxtNacinRezervisanja.getText();
            String napom=jTxtNapomena.getText();
          //   int kupacID = Integer.parseInt(jtxtKupacID.getText().trim());
            String tip=jTxtTipPansiona.getText();
            String nnaz=jTxtNazivGosta.getText();
        
        
            Gost g=new Gost();
            g.setGostID(Integer.parseInt(jTxtGostID.getText()));
                  
        
        Rezervacija n = new Rezervacija();
        n.setBrojRezervacije(brojRez);
    //    n.setDatumOd(datumOd);
      //  n.setDatumDo(datumDo);
        n.setNacinRezervisanja(nacinRez);
        n.setNapomena(napom);
        n.setTipPansiona(tip);
        n.setNazivGosta(nnaz);
        n.setGost(g);
        
        
          
       try {
            Kontroler.vratiInstancuKontrolera().izmeniRezervaciju2(n);
            JOptionPane.showMessageDialog(this, "Rezervacija je uspesno izmenjena");
            osvezi();
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());

          ex.getMessage();
       }
        
    }//GEN-LAST:event_jTxtNazivGostaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijaIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijaIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijaIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmRezervacijaIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmRezervacijaIzmena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtGostID;
    private javax.swing.JTextField jTxtImePrez;
    private javax.swing.JTextField jTxtKontakt;
    private javax.swing.JTextField jTxtNapomena;
    private javax.swing.JTextField jTxtNazGosta;
    private javax.swing.JTextField jTxtNazivGosta;
    private javax.swing.JTextField jTxtTipPansiona;
    private javax.swing.JButton jbtnIzmeniNar;
    private javax.swing.JTextField jtxtBrojRez;
    private javax.swing.JTextField jtxtDatDO;
    private javax.swing.JTextField jtxtDatOD;
    private javax.swing.JTextField jtxtNacinRezervisanja;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
         centrirajFormu();
        Rezervacija n = (Rezervacija) Kontroler.vratiInstancuKontrolera().getMapa().get("rez");
        prikaziRezervaciju(n);
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void prikaziRezervaciju(Rezervacija n) {
        
         jtxtBrojRez.setText(n.getBrojRezervacije()+"");  
         jtxtDatOD.setText(n.getDatumOd()+"");
         jtxtDatDO.setText(n.getDatumDo()+ "");
         jtxtNacinRezervisanja.setText(n.getNacinRezervisanja()+"");
         jTxtNapomena.setText(n.getNapomena()+"");
         jTxtTipPansiona.setText(n.getTipPansiona()+"");
        jTxtNazivGosta.setText(n.getNazivGosta()+"");
        jTxtGostID.setText(n.getGost().getGostID()+"");
        jTxtNazGosta.setEditable(false);
        jTxtImePrez.setEditable(false);
        jTxtKontakt.setEditable(false);
        jTxtImePrez.setText(n.getGost().getImePrezime()+"");
        jTxtNazGosta.setText(n.getGost().getNazivGosta()+"");
        jTxtKontakt.setText(n.getGost().getKontakt()+"");
       
        
    }

    private void osvezi() {
        if(rezervacija!=null) {
            rezervacija.osvezi();
        }
       
    }

   
}
