/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Rezervacija;
import gui.komponente.TblModelRezervacija;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pl.kontroler.Kontroler;

/**
 *
 * @author MMM
 */
public class FmRezervacija extends javax.swing.JFrame {

    /**
     * Creates new form FmNarudzbenica
     */
    public FmRezervacija() {
        initComponents();
        srediFormu();
        centrirajFormu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRezervacija = new javax.swing.JTable();
        jbtnObrisi = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 300));

        jtblRezervacija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblRezervacija.setPreferredSize(new java.awt.Dimension(700, 64));
        jScrollPane1.setViewportView(jtblRezervacija);

        jbtnObrisi.setText("Obrisi rezervaciju");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnObrisi)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnDetalji)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnObrisi)
                    .addComponent(jbtnDetalji))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblRezervacija.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali red!!!");
        } else {
            try {
                TblModelRezervacija model = (TblModelRezervacija) jtblRezervacija.getModel();
                Rezervacija n = (Rezervacija) model.vratiRezervaciju(red);
                Kontroler.vratiInstancuKontrolera().obrisiRezervaciju(n);
                List<Rezervacija> ln = Kontroler.vratiInstancuKontrolera().vratiListuRezervacija();

                jtblRezervacija.setModel(new TblModelRezervacija(ln));

                JOptionPane.showMessageDialog(this, "Rezervacija je obrisana!!!");
                model.obrisiRed(red);
                osvezi();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Rezervacija nije obrisana!!! " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        int red = jtblRezervacija.getSelectedRow();
        TblModelRezervacija model = (TblModelRezervacija) jtblRezervacija.getModel();
        Rezervacija n  = model.vratiRezervaciju(red);
      
        
        Kontroler.vratiInstancuKontrolera().getMapa().put("rez", n);
        FmRezervacijaIzmena fmi = new FmRezervacijaIzmena(null, false, this);
        fmi.setVisible(true);
//        FmUlicaIzmena fmui = new FmUlicaIzmena(null, false, this);
//        fmui.setVisible(true);
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmRezervacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmRezervacija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JTable jtblRezervacija;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
         List<Rezervacija> ln = Kontroler.vratiInstancuKontrolera().vratiListuRezervacija();
        jtblRezervacija.setModel(new TblModelRezervacija(ln));
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
     
    }

    void osvezi() {
        srediFormu();
    }
}
