/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forme;

import domen.PonudaRest;
import domen.Restoran;
import domen.ZahtevPonuda;
import javax.swing.JOptionPane;
import pl.kontroler.Kontroler;


public class FrmIzmenaPonude extends javax.swing.JFrame {

    /**
     * Creates new form FrmIzmenaPonude
     */
    FmPrikazPonuda ponuda;
    public FrmIzmenaPonude(java.awt.Frame parent, boolean modal,  FmPrikazPonuda ponuda) {
       this.ponuda=ponuda;
        initComponents();
        srediFormu();
    }

    public FrmIzmenaPonude() {
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtNazivPonude = new javax.swing.JTextField();
        jTxtZahtevID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTxtRestoranID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtPonudaID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Sacuvaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTxtRestoranID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtRestoranIDKeyPressed(evt);
            }
        });

        jLabel4.setText("RestoranID");

        jLabel1.setText("PonudaID");

        jLabel2.setText("Naziv ponude");

        jLabel3.setText("Zahtev ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtRestoranID, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jTxtPonudaID)
                            .addComponent(jTxtNazivPonude)
                            .addComponent(jTxtZahtevID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtPonudaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNazivPonude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtZahtevID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRestoranID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int pon = Integer.parseInt(jTxtPonudaID.getText().trim());
        String naziv = jTxtNazivPonude.getText();

         int zah = Integer.parseInt(jTxtZahtevID.getText().trim());
       
      
        
        ZahtevPonuda z=new ZahtevPonuda();
        z.setZahtevID(zah);

      //  RezervisaneSobe k = new RezervisaneSobe(r,sobID,brOd,brDec,iznos,naziv,brSo);

        PonudaRest r=new PonudaRest();
        r.setPonudaID(pon);
       
        r.setNazivPonude(naziv);
        r.setZ(z);
        try {
            Kontroler.vratiInstancuKontrolera().izmeniPonudu(r);
            JOptionPane.showMessageDialog(this, "Rezervisana soba je uspesno izmenjena");
            
               osvezi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtRestoranIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRestoranIDKeyPressed
        int pon = Integer.parseInt(jTxtPonudaID.getText().trim());
         String naziv = jTxtNazivPonude.getText();

         int zah = Integer.parseInt(jTxtZahtevID.getText().trim());
       
         int res= Integer.parseInt(jTxtRestoranID.getText().trim());
      
        
        ZahtevPonuda z=new ZahtevPonuda();
        z.setZahtevID(zah);

        Restoran re=new Restoran();
      //  RezervisaneSobe k = new RezervisaneSobe(r,sobID,brOd,brDec,iznos,naziv,brSo);

        re.setRestoranID(res);
        PonudaRest r=new PonudaRest();
        r.setPonudaID(pon);
       
        r.setNazivPonude(naziv);
        r.setZ(z);
        r.setR(re);
       // jButton3.setVisible(false);
        jTxtRestoranID.setEditable(false);
        try {
            Kontroler.vratiInstancuKontrolera().izmeniPonudu2(r);
            JOptionPane.showMessageDialog(this, "Rezervisana soba je uspesno izmenjena");
            
               osvezi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jTxtRestoranIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaPonude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaPonude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaPonude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIzmenaPonude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIzmenaPonude().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtNazivPonude;
    private javax.swing.JTextField jTxtPonudaID;
    private javax.swing.JTextField jTxtRestoranID;
    private javax.swing.JTextField jTxtZahtevID;
    // End of variables declaration//GEN-END:variables

 private void srediFormu() {
         centrirajFormu();
        PonudaRest k = (PonudaRest) Kontroler.vratiInstancuKontrolera().getMapa().get("ponuda_izabrano");
        prikaziPonudu(k);
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void prikaziPonudu(PonudaRest k) {
        jTxtPonudaID.setText(k.getPonudaID()+"");
        jTxtNazivPonude.setText(k.getNazivPonude());
        jTxtZahtevID.setText(k.getZ().getZahtevID()+"");
        jTxtRestoranID.setText(k.getR().getRestoranID()+"");
      
    }

    private void osvezi() {
         if (ponuda != null) {
            ponuda.osvezi();
        }
    }

}
